# Generated by Django 5.1.1 on 2024-10-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_alter_passorder_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passorderitems',
            name='pass_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='passes.passorder'),
        ),
    ]
