# Generated by Django 5.1.1 on 2024-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_alter_passorderitems_pass_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
