# Generated by Django 5.1.1 on 2024-10-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_alter_passorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_cards', to='passes.authuser'),
        ),
    ]
