# Generated by Django 5.1.1 on 2024-10-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('submited_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pass_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.passitem')),
                ('pass_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.passorder')),
            ],
            options={
                'unique_together': {('pass_item', 'pass_order')},
            },
        ),
    ]
