# Generated by Django 5.1.1 on 2024-10-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passitem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
