# Generated by Django 5.1.1 on 2024-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_passitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='passitem',
            name='status',
            field=models.BinaryField(default=True),
        ),
        migrations.AlterField(
            model_name='passitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
