# Generated by Django 5.1.1 on 2024-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_passitem_status_alter_passitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passitem',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
