# Generated by Django 5.1.1 on 2024-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_passitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passitem',
            name='status',
        ),
    ]
