# Generated by Django 5.1.1 on 2024-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_passitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passitem',
            options={'managed': False},
        ),
    ]
